name: Build IsoTarget Cross-Platform

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            output_name: IsoTarget.exe
          - os: macos-13  # Intel Mac for universal compatibility
            output_name: IsoTarget
          - os: macos-latest  # Apple Silicon Mac
            output_name: IsoTarget-ARM

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow

    - name: Build executable (Windows)
      if: runner.os == 'Windows'
      run: |
        pyinstaller --noconfirm --onefile --windowed --name IsoTarget IsoTarget_classroom.py

    - name: Build executable (macOS Intel)
      if: matrix.os == 'macos-13'
      run: |
        pyinstaller --noconfirm --onefile --windowed --name IsoTarget IsoTarget_classroom.py
        pyinstaller --noconfirm --windowed --name IsoTarget-App IsoTarget_classroom.py

    - name: Build executable (macOS Apple Silicon)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --noconfirm --onefile --windowed --name IsoTarget-ARM IsoTarget_classroom.py
        pyinstaller --noconfirm --windowed --name IsoTarget-App-ARM IsoTarget_classroom.py

    - name: Upload Windows executable
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: IsoTarget-Windows
        path: dist/IsoTarget.exe
        retention-days: 30

    - name: Upload macOS Intel executable  
      if: matrix.os == 'macos-13'
      uses: actions/upload-artifact@v4
      with:
        name: IsoTarget-macOS-Intel
        path: dist/IsoTarget
        retention-days: 30

    - name: Upload macOS Intel App Bundle
      if: matrix.os == 'macos-13'
      uses: actions/upload-artifact@v4
      with:
        name: IsoTarget-macOS-Intel-App-Bundle
        path: dist/IsoTarget-App.app/
        retention-days: 30

    - name: Upload macOS Apple Silicon executable  
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: IsoTarget-macOS-AppleSilicon
        path: dist/IsoTarget-ARM
        retention-days: 30

    - name: Upload macOS Apple Silicon App Bundle
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: IsoTarget-macOS-AppleSilicon-App-Bundle
        path: dist/IsoTarget-App-ARM.app/
        retention-days: 30
